[supervisord]
nodaemon=true
logfile=/dev/null

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
priority=10

[include]
files = /etc/supervisor/conf.d/*.conf

