[program:horizon]
command=/usr/local/bin/php /var/www/html/artisan horizon
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
startsecs=5
stopwaitsecs=5
priority=20

